# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: public.ecr.aws/j5w4o3h9/reactapp:latest
        ports:
        - containerPort: 3000

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: webappservice
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodeport to make it accessible through browser
      nodePort: 30100        
